# general settings
name: LL_Refiner_UHD-LOL-4K
model_type: UHD_ImageModel
scale: 1
num_gpu: 4  # set num_gpu: 0 for cpu mode
manual_seed: 1234
use_amp: True

# dataset and data loader settings
datasets:
  train:
    name: TrainSet
    type: Dataset_PairedImage
    dataroot_gt: /data/UHD-LOL-4K/train/high
    dataroot_lq: /data/UHD-LOL-4K/train/low
    geometric_augs: true

    filename_tmpl: '{}'
    io_backend:
      type: disk

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 16
    batch_size_per_gpu: 1

    ### -------------Progressive training--------------------------
    mini_batch_sizes: [6, 4, 4, 2, 1]             # Batch size per gpu   
    iters: [72000, 48000, 24000, 56000, 100000]
    gt_size: 1600   # Max patch size for progressive training
    gt_sizes: [960, 1280, 1280, 1440, 1600]  # Patch sizes for progressive training
    # ### ------------------------------------------------------------

    ### ------- Training on single fixed-patch size 128x128---------
    #mini_batch_sizes: [1]   
    #iters: [150000]
    #gt_size: 1600
    #gt_sizes: [1600]
    ### ------------------------------------------------------------

    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: ValSet
    type: Dataset_PairedImage
    dataroot_gt: /data/UHD-LOL-4K/test/high
    dataroot_lq: /data/UHD-LOL-4K/test/low
    io_backend:
      type: disk

# network structures
network_g:
  type: LL_Refiner
  coarse_dim: 32
  en_feature_num: 48
  en_inter_num: 32
  de_feature_num: 64
  de_inter_num: 32
  sam_number: 2

# path
path:
  pretrain_network_g: "weights/UHD-LOL-4K.pth"
  strict_load_g: true
  resume_state: ~

train:
  total_iter: 300000  # 300000
  warmup_iter: -1 # no warm up
  use_grad_clip: true

  # Split 300k iterations into two cycles. 
  # 1st cycle: fixed 3e-4 LR for 92k iters. 
  # 2nd cycle: cosine annealing (3e-4 to 1e-6) for 208k iters.
  scheduler:
    type: CosineAnnealingRestartCyclicLR
    periods: [92000, 208000] # [46000, 104000]   # [92000, 208000]       
    restart_weights: [1, 1]
    eta_mins: [0.0003,0.000001]   
  
  mixing_augs:
    mixup: true
    mixup_beta: 1.2
    use_identity: true

  optim_g:
    type: AdamW
    lr: !!float 3e-4
    # weight_decay: !!float 1e-4
    betas: [0.9, 0.999]
  
  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1
    reduction: mean

# validation settings
val:
  window_size: 32
  val_freq: !!float 5e3
  save_img: false
  rgb2bgr: true
  use_image: false
  max_minibatch: 8

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
    project: low_light
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
